image: alpine:latest

before_script:
  - apk update
  - apk add python3 py3-pip
  - pip3 install importlib-metadata

pages:
  stage: deploy
  script:
  - cd Source
  - python3 Build.py
  - mv public ../public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
