image: alpine:latest

before_script: |
  apk update
  apk add python3 git

pages:
  stage: deploy
  script: |
    git clone --depth 1 https://gitlab.com/octtspacc/staticoso
    python3 ./staticoso/Source/Build.py
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
